
package com.amazonaws.elasticmapreduce.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JobFlowId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Steps" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}StepConfig" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Apr 21 15:28:27 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jobFlowId",
    "steps"
})
@XmlRootElement(name = "AddJobFlowStepsRequest")
public class AddJobFlowStepsRequest {

    @XmlElement(name = "JobFlowId", required = true)
    protected String jobFlowId;
    @XmlElement(name = "Steps", required = true)
    protected List<StepConfig> steps;

    /**
     * Default constructor
     * 
     */
    public AddJobFlowStepsRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public AddJobFlowStepsRequest(final String jobFlowId, final List<StepConfig> steps) {
        this.jobFlowId = jobFlowId;
        this.steps = steps;
    }

    /**
     * Gets the value of the jobFlowId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobFlowId() {
        return jobFlowId;
    }

    /**
     * Sets the value of the jobFlowId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobFlowId(String value) {
        this.jobFlowId = value;
    }

    public boolean isSetJobFlowId() {
        return (this.jobFlowId!= null);
    }

    /**
     * Gets the value of the steps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the steps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSteps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StepConfig }
     * 
     * 
     */
    public List<StepConfig> getSteps() {
        if (steps == null) {
            steps = new ArrayList<StepConfig>();
        }
        return this.steps;
    }

    public boolean isSetSteps() {
        return ((this.steps!= null)&&(!this.steps.isEmpty()));
    }

    public void unsetSteps() {
        this.steps = null;
    }

    /**
     * Sets the value of the JobFlowId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public AddJobFlowStepsRequest withJobFlowId(String value) {
        setJobFlowId(value);
        return this;
    }

    /**
     * Sets the value of the Steps property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public AddJobFlowStepsRequest withSteps(StepConfig... values) {
        for (StepConfig value: values) {
            getSteps().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the steps property.
     * 
     * @param steps
     *     allowed object is
     *     {@link StepConfig }
     *     
     */
    public void setSteps(List<StepConfig> steps) {
        this.steps = steps;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetJobFlowId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("JobFlowId"));
            json.append(" : ");
            json.append(quoteJSON(getJobFlowId()));
            first = false;
        }
        if (isSetSteps()) {
            if (!first) json.append(", ");
            json.append("\"Steps\" : [");
            java.util.List<StepConfig> stepsList = getSteps();
            int stepsListIndex = 0;
            for (StepConfig steps : stepsList) {
                if (stepsListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(steps.toJSONFragment());
                json.append("}");
                first = false;
                ++stepsListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
