
package com.amazonaws.elasticmapreduce.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JobFlows" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}JobFlowDetail" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Apr 21 15:28:27 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jobFlows"
})
@XmlRootElement(name = "DescribeJobFlowsResult")
public class DescribeJobFlowsResult {

    @XmlElement(name = "JobFlows", required = true)
    protected List<JobFlowDetail> jobFlows;

    /**
     * Default constructor
     * 
     */
    public DescribeJobFlowsResult() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public DescribeJobFlowsResult(final List<JobFlowDetail> jobFlows) {
        this.jobFlows = jobFlows;
    }

    /**
     * Gets the value of the jobFlows property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobFlows property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobFlows().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JobFlowDetail }
     * 
     * 
     */
    public List<JobFlowDetail> getJobFlows() {
        if (jobFlows == null) {
            jobFlows = new ArrayList<JobFlowDetail>();
        }
        return this.jobFlows;
    }

    public boolean isSetJobFlows() {
        return ((this.jobFlows!= null)&&(!this.jobFlows.isEmpty()));
    }

    public void unsetJobFlows() {
        this.jobFlows = null;
    }

    /**
     * Sets the value of the JobFlows property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public DescribeJobFlowsResult withJobFlows(JobFlowDetail... values) {
        for (JobFlowDetail value: values) {
            getJobFlows().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the jobFlows property.
     * 
     * @param jobFlows
     *     allowed object is
     *     {@link JobFlowDetail }
     *     
     */
    public void setJobFlows(List<JobFlowDetail> jobFlows) {
        this.jobFlows = jobFlows;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        java.util.List<JobFlowDetail> jobFlowsList = getJobFlows();
        for (JobFlowDetail jobFlows : jobFlowsList) {
            xml.append("<JobFlows>");
            xml.append(jobFlows.toXMLFragment());
            xml.append("</JobFlows>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetJobFlows()) {
            if (!first) json.append(", ");
            json.append("\"JobFlows\" : [");
            java.util.List<JobFlowDetail> jobFlowsList = getJobFlows();
            int jobFlowsListIndex = 0;
            for (JobFlowDetail jobFlows : jobFlowsList) {
                if (jobFlowsListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(jobFlows.toJSONFragment());
                json.append("}");
                first = false;
                ++jobFlowsListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
