
package com.amazonaws.elasticmapreduce.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobFlowDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobFlowDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JobFlowId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LogUri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExecutionStatusDetail" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}JobFlowExecutionStatusDetail"/>
 *         &lt;element name="Instances" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}JobFlowInstancesDetail"/>
 *         &lt;element name="Steps" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}StepDetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Apr 21 15:28:27 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobFlowDetail", propOrder = {
    "jobFlowId",
    "name",
    "logUri",
    "executionStatusDetail",
    "instances",
    "steps"
})
public class JobFlowDetail {

    @XmlElement(name = "JobFlowId", required = true)
    protected String jobFlowId;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "LogUri")
    protected String logUri;
    @XmlElement(name = "ExecutionStatusDetail", required = true)
    protected JobFlowExecutionStatusDetail executionStatusDetail;
    @XmlElement(name = "Instances", required = true)
    protected JobFlowInstancesDetail instances;
    @XmlElement(name = "Steps")
    protected List<StepDetail> steps;

    /**
     * Default constructor
     * 
     */
    public JobFlowDetail() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public JobFlowDetail(final String jobFlowId, final String name, final String logUri, final JobFlowExecutionStatusDetail executionStatusDetail, final JobFlowInstancesDetail instances, final List<StepDetail> steps) {
        this.jobFlowId = jobFlowId;
        this.name = name;
        this.logUri = logUri;
        this.executionStatusDetail = executionStatusDetail;
        this.instances = instances;
        this.steps = steps;
    }

    /**
     * Gets the value of the jobFlowId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobFlowId() {
        return jobFlowId;
    }

    /**
     * Sets the value of the jobFlowId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobFlowId(String value) {
        this.jobFlowId = value;
    }

    public boolean isSetJobFlowId() {
        return (this.jobFlowId!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the logUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogUri() {
        return logUri;
    }

    /**
     * Sets the value of the logUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogUri(String value) {
        this.logUri = value;
    }

    public boolean isSetLogUri() {
        return (this.logUri!= null);
    }

    /**
     * Gets the value of the executionStatusDetail property.
     * 
     * @return
     *     possible object is
     *     {@link JobFlowExecutionStatusDetail }
     *     
     */
    public JobFlowExecutionStatusDetail getExecutionStatusDetail() {
        return executionStatusDetail;
    }

    /**
     * Sets the value of the executionStatusDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobFlowExecutionStatusDetail }
     *     
     */
    public void setExecutionStatusDetail(JobFlowExecutionStatusDetail value) {
        this.executionStatusDetail = value;
    }

    public boolean isSetExecutionStatusDetail() {
        return (this.executionStatusDetail!= null);
    }

    /**
     * Gets the value of the instances property.
     * 
     * @return
     *     possible object is
     *     {@link JobFlowInstancesDetail }
     *     
     */
    public JobFlowInstancesDetail getInstances() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobFlowInstancesDetail }
     *     
     */
    public void setInstances(JobFlowInstancesDetail value) {
        this.instances = value;
    }

    public boolean isSetInstances() {
        return (this.instances!= null);
    }

    /**
     * Gets the value of the steps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the steps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSteps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StepDetail }
     * 
     * 
     */
    public List<StepDetail> getSteps() {
        if (steps == null) {
            steps = new ArrayList<StepDetail>();
        }
        return this.steps;
    }

    public boolean isSetSteps() {
        return ((this.steps!= null)&&(!this.steps.isEmpty()));
    }

    public void unsetSteps() {
        this.steps = null;
    }

    /**
     * Sets the value of the JobFlowId property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public JobFlowDetail withJobFlowId(String value) {
        setJobFlowId(value);
        return this;
    }

    /**
     * Sets the value of the Name property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public JobFlowDetail withName(String value) {
        setName(value);
        return this;
    }

    /**
     * Sets the value of the LogUri property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public JobFlowDetail withLogUri(String value) {
        setLogUri(value);
        return this;
    }

    /**
     * Sets the value of the ExecutionStatusDetail property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public JobFlowDetail withExecutionStatusDetail(JobFlowExecutionStatusDetail value) {
        setExecutionStatusDetail(value);
        return this;
    }

    /**
     * Sets the value of the Instances property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public JobFlowDetail withInstances(JobFlowInstancesDetail value) {
        setInstances(value);
        return this;
    }

    /**
     * Sets the value of the Steps property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public JobFlowDetail withSteps(StepDetail... values) {
        for (StepDetail value: values) {
            getSteps().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the steps property.
     * 
     * @param steps
     *     allowed object is
     *     {@link StepDetail }
     *     
     */
    public void setSteps(List<StepDetail> steps) {
        this.steps = steps;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetJobFlowId()) {
            xml.append("<JobFlowId>");
            xml.append(escapeXML(getJobFlowId()));
            xml.append("</JobFlowId>");
        }
        if (isSetName()) {
            xml.append("<Name>");
            xml.append(escapeXML(getName()));
            xml.append("</Name>");
        }
        if (isSetLogUri()) {
            xml.append("<LogUri>");
            xml.append(escapeXML(getLogUri()));
            xml.append("</LogUri>");
        }
        if (isSetExecutionStatusDetail()) {
            JobFlowExecutionStatusDetail  executionStatusDetail = getExecutionStatusDetail();
            xml.append("<ExecutionStatusDetail>");
            xml.append(executionStatusDetail.toXMLFragment());
            xml.append("</ExecutionStatusDetail>");
        } 
        if (isSetInstances()) {
            JobFlowInstancesDetail  instances = getInstances();
            xml.append("<Instances>");
            xml.append(instances.toXMLFragment());
            xml.append("</Instances>");
        } 
        java.util.List<StepDetail> stepsList = getSteps();
        for (StepDetail steps : stepsList) {
            xml.append("<Steps>");
            xml.append(steps.toXMLFragment());
            xml.append("</Steps>");
        }
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetJobFlowId()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("JobFlowId"));
            json.append(" : ");
            json.append(quoteJSON(getJobFlowId()));
            first = false;
        }
        if (isSetName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Name"));
            json.append(" : ");
            json.append(quoteJSON(getName()));
            first = false;
        }
        if (isSetLogUri()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("LogUri"));
            json.append(" : ");
            json.append(quoteJSON(getLogUri()));
            first = false;
        }
        if (isSetExecutionStatusDetail()) {
            if (!first) json.append(", ");
            json.append("\"ExecutionStatusDetail\" : {");
            JobFlowExecutionStatusDetail  executionStatusDetail = getExecutionStatusDetail();


            json.append(executionStatusDetail.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetInstances()) {
            if (!first) json.append(", ");
            json.append("\"Instances\" : {");
            JobFlowInstancesDetail  instances = getInstances();


            json.append(instances.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetSteps()) {
            if (!first) json.append(", ");
            json.append("\"Steps\" : [");
            java.util.List<StepDetail> stepsList = getSteps();
            int stepsListIndex = 0;
            for (StepDetail steps : stepsList) {
                if (stepsListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(steps.toJSONFragment());
                json.append("}");
                first = false;
                ++stepsListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
