
package com.amazonaws.elasticmapreduce.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LogUri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Instances" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}JobFlowInstancesConfig"/>
 *         &lt;element name="Steps" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}StepConfig" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Apr 21 15:28:27 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "logUri",
    "instances",
    "steps"
})
@XmlRootElement(name = "RunJobFlowRequest")
public class RunJobFlowRequest {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "LogUri")
    protected String logUri;
    @XmlElement(name = "Instances", required = true)
    protected JobFlowInstancesConfig instances;
    @XmlElement(name = "Steps")
    protected List<StepConfig> steps;

    /**
     * Default constructor
     * 
     */
    public RunJobFlowRequest() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public RunJobFlowRequest(final String name, final String logUri, final JobFlowInstancesConfig instances, final List<StepConfig> steps) {
        this.name = name;
        this.logUri = logUri;
        this.instances = instances;
        this.steps = steps;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the logUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogUri() {
        return logUri;
    }

    /**
     * Sets the value of the logUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogUri(String value) {
        this.logUri = value;
    }

    public boolean isSetLogUri() {
        return (this.logUri!= null);
    }

    /**
     * Gets the value of the instances property.
     * 
     * @return
     *     possible object is
     *     {@link JobFlowInstancesConfig }
     *     
     */
    public JobFlowInstancesConfig getInstances() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobFlowInstancesConfig }
     *     
     */
    public void setInstances(JobFlowInstancesConfig value) {
        this.instances = value;
    }

    public boolean isSetInstances() {
        return (this.instances!= null);
    }

    /**
     * Gets the value of the steps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the steps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSteps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StepConfig }
     * 
     * 
     */
    public List<StepConfig> getSteps() {
        if (steps == null) {
            steps = new ArrayList<StepConfig>();
        }
        return this.steps;
    }

    public boolean isSetSteps() {
        return ((this.steps!= null)&&(!this.steps.isEmpty()));
    }

    public void unsetSteps() {
        this.steps = null;
    }

    /**
     * Sets the value of the Name property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunJobFlowRequest withName(String value) {
        setName(value);
        return this;
    }

    /**
     * Sets the value of the LogUri property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunJobFlowRequest withLogUri(String value) {
        setLogUri(value);
        return this;
    }

    /**
     * Sets the value of the Instances property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public RunJobFlowRequest withInstances(JobFlowInstancesConfig value) {
        setInstances(value);
        return this;
    }

    /**
     * Sets the value of the Steps property.
     * 
     * @param values
     * @return
     *     this instance
     */
    public RunJobFlowRequest withSteps(StepConfig... values) {
        for (StepConfig value: values) {
            getSteps().add(value);
        }
        return this;
    }

    /**
     * Sets the value of the steps property.
     * 
     * @param steps
     *     allowed object is
     *     {@link StepConfig }
     *     
     */
    public void setSteps(List<StepConfig> steps) {
        this.steps = steps;
    }
    


    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetName()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("Name"));
            json.append(" : ");
            json.append(quoteJSON(getName()));
            first = false;
        }
        if (isSetLogUri()) {
            if (!first) json.append(", ");
            json.append(quoteJSON("LogUri"));
            json.append(" : ");
            json.append(quoteJSON(getLogUri()));
            first = false;
        }
        if (isSetInstances()) {
            if (!first) json.append(", ");
            json.append("\"Instances\" : {");
            JobFlowInstancesConfig  instances = getInstances();


            json.append(instances.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetSteps()) {
            if (!first) json.append(", ");
            json.append("\"Steps\" : [");
            java.util.List<StepConfig> stepsList = getSteps();
            int stepsListIndex = 0;
            for (StepConfig steps : stepsList) {
                if (stepsListIndex > 0) json.append(", ");
                json.append("{");
                json.append("");
                json.append(steps.toJSONFragment());
                json.append("}");
                first = false;
                ++stepsListIndex;
            }
            json.append("]");
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
