
package com.amazonaws.elasticmapreduce.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StepDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StepDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StepConfig" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}StepConfig"/>
 *         &lt;element name="ExecutionStatusDetail" type="{http://elasticmapreduce.amazonaws.com/doc/2009-03-31}StepExecutionStatusDetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * Generated by AWS Code Generator
 * <p/>
 * Tue Apr 21 15:28:27 PDT 2009
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StepDetail", propOrder = {
    "stepConfig",
    "executionStatusDetail"
})
public class StepDetail {

    @XmlElement(name = "StepConfig", required = true)
    protected StepConfig stepConfig;
    @XmlElement(name = "ExecutionStatusDetail", required = true)
    protected StepExecutionStatusDetail executionStatusDetail;

    /**
     * Default constructor
     * 
     */
    public StepDetail() {
        super();
    }

    /**
     * Value constructor
     * 
     */
    public StepDetail(final StepConfig stepConfig, final StepExecutionStatusDetail executionStatusDetail) {
        this.stepConfig = stepConfig;
        this.executionStatusDetail = executionStatusDetail;
    }

    /**
     * Gets the value of the stepConfig property.
     * 
     * @return
     *     possible object is
     *     {@link StepConfig }
     *     
     */
    public StepConfig getStepConfig() {
        return stepConfig;
    }

    /**
     * Sets the value of the stepConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepConfig }
     *     
     */
    public void setStepConfig(StepConfig value) {
        this.stepConfig = value;
    }

    public boolean isSetStepConfig() {
        return (this.stepConfig!= null);
    }

    /**
     * Gets the value of the executionStatusDetail property.
     * 
     * @return
     *     possible object is
     *     {@link StepExecutionStatusDetail }
     *     
     */
    public StepExecutionStatusDetail getExecutionStatusDetail() {
        return executionStatusDetail;
    }

    /**
     * Sets the value of the executionStatusDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link StepExecutionStatusDetail }
     *     
     */
    public void setExecutionStatusDetail(StepExecutionStatusDetail value) {
        this.executionStatusDetail = value;
    }

    public boolean isSetExecutionStatusDetail() {
        return (this.executionStatusDetail!= null);
    }

    /**
     * Sets the value of the StepConfig property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public StepDetail withStepConfig(StepConfig value) {
        setStepConfig(value);
        return this;
    }

    /**
     * Sets the value of the ExecutionStatusDetail property.
     * 
     * @param value
     * @return
     *     this instance
     */
    public StepDetail withExecutionStatusDetail(StepExecutionStatusDetail value) {
        setExecutionStatusDetail(value);
        return this;
    }
    

    /**
     * 
     * XML fragment representation of this object
     * 
     * @return XML fragment for this object. Name for outer
     * tag expected to be set by calling method. This fragment
     * returns inner properties representation only
     */
    protected String toXMLFragment() {
        StringBuffer xml = new StringBuffer();
        if (isSetStepConfig()) {
            StepConfig  stepConfig = getStepConfig();
            xml.append("<StepConfig>");
            xml.append(stepConfig.toXMLFragment());
            xml.append("</StepConfig>");
        } 
        if (isSetExecutionStatusDetail()) {
            StepExecutionStatusDetail  executionStatusDetail = getExecutionStatusDetail();
            xml.append("<ExecutionStatusDetail>");
            xml.append(executionStatusDetail.toXMLFragment());
            xml.append("</ExecutionStatusDetail>");
        } 
        return xml.toString();
    }

    /**
     * 
     * Escape XML special characters
     */
    private String escapeXML(String string) {
        StringBuffer sb = new StringBuffer();
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '&':
                sb.append("&amp;");
                break;
            case '<':
                sb.append("&lt;");
                break;
            case '>':
                sb.append("&gt;");
                break;
            case '\'':
                sb.append("&#039;");
                break;
            case '"':
                sb.append("&quot;");
                break;
            default:
                sb.append(c);
            }
        }
        return sb.toString();
    }



    /**
     *
     * JSON fragment representation of this object
     *
     * @return JSON fragment for this object. Name for outer
     * object expected to be set by calling method. This fragment
     * returns inner properties representation only
     *
     */
    protected String toJSONFragment() {
        StringBuffer json = new StringBuffer();
        boolean first = true;
        if (isSetStepConfig()) {
            if (!first) json.append(", ");
            json.append("\"StepConfig\" : {");
            StepConfig  stepConfig = getStepConfig();


            json.append(stepConfig.toJSONFragment());
            json.append("}");
            first = false;
        }
        if (isSetExecutionStatusDetail()) {
            if (!first) json.append(", ");
            json.append("\"ExecutionStatusDetail\" : {");
            StepExecutionStatusDetail  executionStatusDetail = getExecutionStatusDetail();


            json.append(executionStatusDetail.toJSONFragment());
            json.append("}");
            first = false;
        }
        return json.toString();
    }

    /**
     *
     * Quote JSON string
     */
    private String quoteJSON(String string) {
        StringBuffer sb = new StringBuffer();
        sb.append("\"");
        int length = string.length();
        for (int i = 0; i < length; ++i) {
            char c = string.charAt(i);
            switch (c) {
            case '"':
                sb.append("\\\"");
                break;
            case '\\':
                sb.append("\\\\");
                break;
            case '/':
                sb.append("\\/");
                break;
            case '\b':
                sb.append("\\b");
                break;
            case '\f':
                sb.append("\\f");
                break;
            case '\n':
                sb.append("\\n");
                break;
            case '\r':
                sb.append("\\r");
                break;
            case '\t':
                sb.append("\\t");
                break;
            default:
                if (c <  ' ') {
                    sb.append("\\u" + String.format("%03x", Integer.valueOf(c)));
                } else {
                sb.append(c);
            }
        }
        }
        sb.append("\"");
        return sb.toString();
    }


}
